export default [
	{
		path:'/home/documents/Ebeard',
		component:"Documents/Ebeard/index",
	},{
		path:'/home/documents/EcodeHighlight',
		component:"Documents/EcodeHighlight/index",
	},{
		path:'/home/documents/EcolorPicker',
		component:"Documents/EcolorPicker/index",
	},{
		path:'/home/documents/Edrawer',
		component:"Documents/Edrawer/index",
	},{
		path:"/home/documents/ElistHoc",
		component:"Documents/ElistHoc/index",
	},{
		path:"/home/documents/EtreeHoc"	,
		component:"Documents/EtreeHoc/index",
	},{
		path:"/home/documents/Eviewer",
		component:"Documents/Eviewer/index"
	},{
		path:"/home/documents/EformHoc",
		component:"Documents/EformHoc/index"
	},{
		path:"/home/documents/EheaderHoc",
		component:"Documents/EheaderHoc/index"
	},{
		path:"/home/documents/Eloading",
		component:"Documents/Eloading/index"
	},{
		path:"/home/documents/EsearchListHoc",
		component:"Documents/EsearchListHoc/index"
	},{
		path:"/home/documents/EText",
		component:"Documents/EText/index"
	},{
		path:"/home/documents/EuploadImg",
		component:"Documents/EuploadImg/index"
	},{
		path:"/home/documents/EFabButton",
		component:"Documents/EFabButton/index"
	}
]

