export const  LOGIN_REQUEST = "LOGIN_REQUEST";
export const  LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const  LOGIN_ERROR = "LOGIN_ERROR";


export const  LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const  LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const  LOGOUT_ERROR = "LOGOUT_ERROR";


/**
 * dataList demo
*/
export const DATALIST_REQUEST = "DATALIST_REQUEST";
export const DATALIST_LOADING = "DATALIST_LOADING";
export const DATALIST = "DATALIST";
export const DATALIST_DELETE_LOADING = "DATALIST_DELETE_LOADING";
export const DATALIST_DELETE = "DATALIST_DELETE";
export const DATALIST_UPDATE_LOADING = "DATALIST_UPDATE_LOADING";
export const DATALIST_UPDATE = "DATALIST_UPDATE";
export const DATALIST_ADD = "DATALIST_ADD";
export const DATALIST_ADD_LOADING = "DATALIST_ADD_LOADING";